add vim mode   and yaml config
TheWinds/devgo pull request #2
Opened 2021-07-01 10:34 UTC by mainjzb

add vim mode
add yaml config

2021-07-01 10:55 UTC, TheWinds requested changes
very nice

2021-07-01 10:55 UTC, TheWinds commented on config/toml.go
> +		err = ioutil.WriteFile(confPath, []byte(defaultTomlConfig), 0644)
这里可以兼容一下老的 `~/.devgo ` 配置文件这样老版本就升级就不会有什么问题问题了~

2021-07-01 16:03 UTC, mainjzb reviewed
compatible old toml config file

2021-07-02 02:15 UTC, TheWinds requested changes

2021-07-02 02:15 UTC, TheWinds commented on utils/file.go
> +package utils
没必要加一个utils包，一是含义不明确，二是因为判断文件是否存在只会在load config的时候用到

2021-07-02 10:11 UTC, TheWinds commented
LGTM

2021-07-02 10:12 UTC, merged